@baseApiUrl=http://127.0.0.1:20008/v1/api
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTBiYzQ5YjMwNTI3MzFmN2Q1NjE5YzciLCJlbWFpbCI6InNob3BkZXYyNUBnbWFpbC5jb20iLCJpYXQiOjE3NzkxNTYxMzMsImV4cCI6MTc3OTMyODkzM30.O1InbwLoqrFgy97zQCFeijRDGZHXymmk-zmasA-PoQ0

# Create a new clothing product.
POST {{baseApiUrl}}/product/create
Content-Type: application/json
x-api-key: xxxxx
x-client-id: 6a0bc49b3052731f7d5619c7
Authorization: {{accessToken}}

{
  "productName": "Oversized Cotton Hoodie II",
  "productThumb": "https://cdn.example.com/products/hoodie-black.jpg",
  "productDescription": "Premium oversized hoodie made from 100% cotton.",
  "productPrice": 389.99,
  "productQuantity": 120,
  "productType": "Clothing",
  "productShop": "6829d8f7b8a2d1f4c8a91234",
  "productAttributes": {
    "brand": "UrbanWear",
    "size": "L",
    "material": "Cotton"
  }
}