@baseApiUrl=http://127.0.0.1:20008/v1/api/access
@email=luutanhung@gmail.com
@password=!'2@;_Ltg42aK8m6
@acceptLanguage=vi

### Shop logins successfully.
POST {{baseApiUrl}}/login
Content-Type: application/json
Accept-Language: {{acceptLanguage}}
x-api-key: xxxxx

{
  "email": "{{email}}",
  "password": "{{password}}"
}