@baseApiUrl=http://127.0.0.1:20008/v1/api
@shopName=ShopDEV
@shopEmail=shopdev21@gmail.com

@shopPassword=!'2@;_Ltg42aK8m6
@acceptLanguage=vi

### Shop logins successfully.
POST {{baseApiUrl}}/shop/login
Content-Type: application/json
Accept-Language: {{acceptLanguage}}
x-api-key: xxxxx

{
  "email": "{{shopEmail}}",
  "password": "{{shopPassword}}"
}