@base_api_url=http://127.0.0.1:20008/v1/api

### Shop logouts successfully.
POST {{base_api_url}}/shop/logout
Content-Type: application/json
x-client-id: 6a091336e0905906521bded5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTA5MTMzNmUwOTA1OTA2NTIxYmRlZDUiLCJlbWFpbCI6InNob3BkZXYyMUBnbWFpbC5jb20iLCJpYXQiOjE3Nzg5OTM4ODUsImV4cCI6MTc3OTE2NjY4NX0.AAOKCxu4s2IM-2Lp77YexRG6NEvqBr1ZNi0np4wqeDU