@baseApiUrl=http://127.0.0.1:20008/v1/api/access
@email=shopdev25@gmail.com
@password=!'2@;_Ltg42aK8m6

### Registers a new user successfully.
POST {{baseApiUrl}}/register
Content-Type: application/json
x-api-key: xxxxx

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Registers a new shop should fail when missing shop's email.
POST {{baseApiUrl}}/register
Content-Type: application/json
x-api-key: xxxxx

{
  "email": "{{email}}"
  "password": "{{password}}"
}