@base_api_url=http://127.0.0.1:20008/v1/api
@shop_name=ShopDEV
@shop_password=!'2@;_Ltg42aK8m6

### Registers a new shop successfully.
POST {{base_api_url}}/shop/signup
Content-Type: application/json
x-api-key: xxxxx

{
  "name": "ShopDev",
  "email": "shopdev13@gmail.com",
  "password": "shopdevsecret"
}

### Registers a new shop should fail when missing shop's email.
POST {{base_api_url}}/shop/signup
Content-Type: application/json
x-api-key: xxxxx

{
  "name": "{{shop_name}}",
  "email": "shopdev21@gmail.com",
  "password": "{{shop_password}}"
}