export const ResCode = {
  // Generics.
  // 200 range.
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",

  // 400 range.
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_REQUEST: "INVALID_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  TOO_MANY_REQUEST: "TOO_MANY_REQUEST",
  CONFLICT: "CONFLICT",

  // Client ID.
  CLIENT_ID_REQUIRED: "CLIENT_ID_REQUIRED",

  // JSON.
  INVALID_JSON: "INVALID_JSON",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  UNAUTHENTICATED: "UNAUTHENTICATED",

  // Mongoose.
  INVALID_OBJECT_ID: "INVALID_OBJECT_ID",
  INVALID_ID: "INVALID_ID",

  // User.
  USER_INVALID: "USER_INVALID",

  // Access Token.
  ACCESS_TOKEN_REQUIRED: "ACCESS_TOKEN_REQUIRED",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",

  // Refresh Token.
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  REFRESH_TOKEN_NOT_FOUND: "REFRESH_TOKEN_NOT_FOUND",
  REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",

  /*
   * Entity-focused.
   */
  // Name.
  NAME_REQUIRED: "NAME_REQUIRED",
  NAME_INVALID_TYPE: "NAME_INVALID_TYPE",

  // Email.
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_INVALID_TYPE: "EMAIL_INVALID_TYPE",
  EMAIL_INVALID: "EMAIL_INVALID",

  // Password.
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  PASSWORD_INVALID_TYPE: "PASSWORD_INVALID_TYPE",
  PASSWORD_INVALID: "PASSWORD_INVALID",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_MISSING_UPPERCASE: "PASSWORD_MISSING_UPPERCASE",
  PASSWORD_MISSING_LOWERCASE: "PASSWORD_MISSING_LOWERCASE",
  PASSWORD_MISSING_NUMBER: "PASSWORD_MISSING_NUMBER",
  PASSWORD_MISSING_SPECIAL_CHAR: "PASSWORD_MISSING_SPECIAL_CHAR",

  // User.
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_IS_NOT_REGISTERED: "USER_IS_NOT_REGISTERED",
  USER_NOT_LOGGED_IN: "USER_NOT_LOGGED_IN",

  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",

  // Key Token.
  KEY_TOKEN_ALREADY_EXISTS: "KEY_TOKEN_ALREADY_EXISTS",
  KEY_TOKEN_NOT_FOUND: "KEY_TOKEN_NOT_FOUND",

  // Shop.
  SHOP_NOT_OWNED_BY_USER: "SHOP_NOT_OWNED_BY_USER",
  SHOP_REGISTER_FAILED: "SHOP_REGISTER_FAILED",

  SHOP_NOT_FOUND: "SHOP_NOT_FOUND",
  SHOP_INVALID_NAME: "SHOP_INVALID_NAME",
  SHOP_IS_NOT_REGISTERED: "SHOP_IS_NOT_REGISTERED",
  SHOP_ALREADY_EXISTS: "SHOP_ALREADY_EXISTS",
  SHOP_ALREADY_REGISTERED: "SHOP_ALREADY_REGISTERED",
  SHOP_REGISTER_SUCCESS: "SHOP_REGISTER_SUCCESS",

  SHOP_NOT_LOGGED_IN: "SHOP_NOT_LOGGED_IN",
  SHOP_LOGIN_SUCCESS: "SHOP_LOGIN_SUCCESS",

  SHOP_LOGOUT_SUCCESS: "SHOP_LOGOUT_SUCCESS",

  // Product.
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",

  PRODUCT_NAME_REQUIRED: "PRODUCT_NAME_REQUIRED",
  PRODUCT_NAME_INVALID_TYPE: "PRODUCT_NAME_INVALID_TYPE",

  PRODUCT_THUMB_REQUIRED: "PRODUCT_THUMB_REQUIRED",
  PRODUCT_THUMB_INVALID_TYPE: "PRODUCT_THUMB_INVALID_TYPE",

  PRODUCT_SHOP_REQUIRED: "PRODUCT_SHOP_REQUIRED",
  PRODUCT_SHOP_INVALID_TYPE: "PRODUCT_SHOP_INVALID_TYPE",

  PRODUCT_TYPE_INVALID: "PRODUCT_TYPE_INVALID",

  PRODUCT_PRICE_REQUIRED: "PRODUCT_PRICE_REQUIRED",
  PRODUCT_PRICE_INVALID_TYPE: "PRODUCT_PRICE_INVALID_TYPE",
  PRODUCT_PRICE_MUST_BE_POSITIVE: "PRODUCT_PRICE_MUST_BE_POSITIVE",

  PRODUCT_QUANTITY_INVALID_TYPE: "PRODUCT_QUANTITY_INVALID_TYPE",
  PRODUCT_QUANTITY_MUST_BE_POSITIVE: "PRODUCT_QUANTITY_MUST_BE_POSITIVE",

  PRODUCT_TYPE_UNSUPPORTED: "PRODUCT_TYPE_UNSUPPORTED",
  PRODUCT_AVERAGE_RATING_MUST_BE_GREATER_THAN_OR_EQUAL_TO_ONE:
    "PRODUCT_AVERAGE_RATING_MUST_BE_GREATER_THAN_OR_EQUAL_TO_ONE",
  PRODUCT_AVERAGE_RATING_MUST_BE_LESS_THAN_OR_EQUAL_TO_FIVE:
    "PRODUCT_AVERAGE_RATING_MUST_BE_LESS_THAN_OR_EQUAL_TO_FIVE",

  PRODUCT_CREATION_SUCCESS: "PRODUCT_CREATION_SUCCESS",
  PRODUCT_CREATION_FAILURE: "PRODUCT_CREATION_FAILURE",

  PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",

  PRODUCT_FIND_SUCCESS: "PRODUCT_FIND_SUCCESS",

  PRODUCT_SEARCH_PUBLISHED_SUCCESS: "PRODUCT_SEARCH_PUBLISHED_SUCCESS",

  // Product publish.
  PRODUCT_ALREADY_PUBLISHED: "PRODUCT_ALREADY_PUBLISHED",
  PRODUCT_PUBLISH_SUCCESS: "PRODUCT_PUBLISH_SUCCESS",

  // Product unpublish.
  PRODUCT_ALREADY_DRAFT: "PRODUCT_ALREADY_DRAFT",
  PRODUCT_UNPUBLISH_SUCCESS: "PRODUCT_UNPUBLISH_SUCCESS",

  PRODUCT_FIND_DRAFT_PRODUCTS_SUCCESS: "PRODUCT_FIND_DRAFT_PRODUCTS_SUCCESS",
  PRODUCT_FIND_PUBLISHED_PRODUCTS_SUCCESS:
    "PRODUCT_FIND_PUBLISHED_PRODUCTS_SUCCESS",

  // Clothing products.
  PRODUCT_CLOTHING_CREATION_FAILURE: "PRODUCT_CLOTHING_CREATION_FAILURE",
  PRODUCT_CLOTHING_CREATION_SUCCESS: "PRODUCT_CLOTHING_CREATION_SUCCESS",

  // Electronic products.
  PRODUCT_ELECTRONIC_CREATION_FAILURE: "PRODUCT_ELECTRONIC_CREATION_FAILURE",

  PRODUCT_FURNITURE_CREATION_FAILURE: "PRODUCT_FURNITURE_CREATION_FAILURE",

  /**
   * Inventory.
   */
  INVENTORY_CREATE_FAILED: "INVENTORY_CREATE_FAILED",
} as const;
