export const ResCode = {
  // Generics.
  // 200 range.
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",

  // 400 range.
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_REQUEST: "INVALID_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  TOO_MANY_REQUEST: "TOO_MANY_REQUEST",
  CONFLICT: "CONFLICT",

  // Client ID.
  CLIENT_ID_REQUIRED: "CLIENT_ID_REQUIRED",

  // JSON.
  INVALID_JSON: "INVALID_JSON",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  UNAUTHENTICATED: "UNAUTHENTICATED",

  // User.
  USER_INVALID: "USER_INVALID",

  // Access Token.
  ACCESS_TOKEN_REQUIRED: "ACCESS_TOKEN_REQUIRED",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",

  // Refresh Token.
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  REFRESH_TOKEN_NOT_FOUND: "REFRESH_TOKEN_NOT_FOUND",
  REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",

  /*
   * Entity-focused.
   */
  // Name.
  NAME_REQUIRED: "NAME_REQUIRED",
  NAME_INVALID_TYPE: "NAME_INVALID_TYPE",

  // Email.
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_INVALID_TYPE: "EMAIL_INVALID_TYPE",
  EMAIL_INVALID: "EMAIL_INVALID",

  // Password.
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  PASSWORD_INVALID_TYPE: "PASSWORD_INVALID_TYPE",
  PASSWORD_INVALID: "PASSWORD_INVALID",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_MISSING_UPPERCASE: "PASSWORD_MISSING_UPPERCASE",
  PASSWORD_MISSING_LOWERCASE: "PASSWORD_MISSING_LOWERCASE",
  PASSWORD_MISSING_NUMBER: "PASSWORD_MISSING_NUMBER",
  PASSWORD_MISSING_SPECIAL_CHAR: "PASSWORD_MISSING_SPECIAL_CHAR",

  // Key Token.
  KEY_TOKEN_ALREADY_EXISTS: "KEY_TOKEN_ALREADY_EXISTS",
  KEY_TOKEN_NOT_FOUND: "KEY_TOKEN_NOT_FOUND",

  // Shop.
  SHOP_NOT_FOUND: "SHOP_NOT_FOUND",
  SHOP_INVALID_NAME: "SHOP_INVALID_NAME",
  SHOP_IS_NOT_REGISTERED: "SHOP_IS_NOT_REGISTERED",
  SHOP_ALREADY_EXISTS: "SHOP_ALREADY_EXISTS",
  SHOP_ALREADY_REGISTERED: "SHOP_ALREADY_REGISTERED",
  SHOP_REGISTRATION_SUCCESS: "SHOP_REGISTRATION_SUCCESS",

  SHOP_NOT_LOGGED_IN: "SHOP_NOT_LOGGED_IN",
  SHOP_LOGIN_SUCCESS: "SHOP_LOGIN_SUCCESS",

  SHOP_LOGOUT_SUCCESS: "SHOP_LOGOUT_SUCCESS",

  // Product.
  PRODUCT_NAME_REQUIRED: "PRODUCT_NAME_REQUIRED",
  PRODUCT_NAME_INVALID_TYPE: "PRODUCT_NAME_INVALID_TYPE",

  PRODUCT_THUMB_REQUIRED: "PRODUCT_THUMB_REQUIRED",
  PRODUCT_THUMB_INVALID_TYPE: "PRODUCT_THUMB_INVALID_TYPE",

  PRODUCT_SHOP_REQUIRED: "PRODUCT_SHOP_REQUIRED",
  PRODUCT_SHOP_INVALID_TYPE: "PRODUCT_SHOP_INVALID_TYPE",

  PRODUCT_TYPE_INVALID: "PRODUCT_TYPE_INVALID",

  PRODUCT_PRICE_REQUIRED: "PRODUCT_PRICE_REQUIRED",
  PRODUCT_PRICE_INVALID_TYPE: "PRODUCT_PRICE_INVALID_TYPE",
  PRODUCT_PRICE_MUST_BE_POSITIVE: "PRODUCT_PRICE_MUST_BE_POSITIVE",

  PRODUCT_QUANTITY_INVALID_TYPE: "PRODUCT_QUANTITY_INVALID_TYPE",
  PRODUCT_QUANTITY_MUST_BE_POSITIVE: "PRODUCT_QUANTITY_MUST_BE_POSITIVE",

  PRODUCT_TYPE_UNSUPPORTED: "PRODUCT_TYPE_UNSUPPORTED",

  PRODUCT_CREATION_SUCCESS: "PRODUCT_CREATION_SUCCESS",
  PRODUCT_CREATION_FAILURE: "PRODUCT_CREATION_FAILURE",

  // Clothing products.
  PRODUCT_CLOTHING_CREATION_FAILURE: "PRODUCT_CLOTHING_CREATION_FAILURE",
  PRODUCT_CLOTHING_CREATION_SUCCESS: "PRODUCT_CLOTHING_CREATION_SUCCESS",

  // Electronic products.
  PRODUCT_ELECTRONIC_CREATION_FAILURE: "PRODUCT_ELECTRONIC_CREATION_FAILURE",

  PRODUCT_FURNITURE_CREATION_FAILURE: "PRODUCT_FURNITURE_CREATION_FAILURE",
} as const;
