/**
 * [ENTITY]_[ACTION]_[STATUS(noun/adj)]
 */

export const ResCode = {
  // Generics.
  // 200 range.
  SUCCESS: "SUCCESS",
  CREATED: "CREATED",

  // 400 range.
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_REQUEST: "INVALID_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  TOO_MANY_REQUEST: "TOO_MANY_REQUEST",
  CONFLICT: "CONFLICT",

  // Client ID.
  CLIENT_ID_REQUIRED: "CLIENT_ID_REQUIRED",

  // JSON.
  INVALID_JSON: "INVALID_JSON",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  UNAUTHENTICATED: "UNAUTHENTICATED",

  // Rate Limiter.
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Mongoose.
  ID_IS_EMPTY: "ID_IS_EMPTY",
  INVALID_OBJECT_ID: "INVALID_OBJECT_ID",
  INVALID_ID: "INVALID_ID",

  /**
   * Queue.
   */
  JOB_NAME_UNKNOWN: "JOB_NAME_UNKNOWN",

  /**
   * Notifications.
   */
  NOTIFICATION_CREATE_FAILED: "NOTIFICATION_CREATE_FAILED",
  NOTIFICATION_CREATE_SUCCEEDED: "NOTIFICATION_CREATE_SUCCEEDED",

  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",

  // User.
  USER_INVALID: "USER_INVALID",

  // Device.
  DEVICE_ID_REQUIRED: "DEVICE_ID_REQUIRED",
  DEVICE_ID_INVALID: "DEVICE_ID_INVALID",

  // Access Token.
  ACCESS_TOKEN_REQUIRED: "ACCESS_TOKEN_REQUIRED",
  ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID: "ACCESS_TOKEN_INVALID",

  // Refresh Token.
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  REFRESH_TOKEN_NOT_FOUND: "REFRESH_TOKEN_NOT_FOUND",
  REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",

  /*
   * Entity-focused.
   */
  // Name.
  USER_NAME_REQUIRED: "USER_NAME_REQUIRED",
  USER_NAME_INVALID_TYPE: "USER_NAME_INVALID_TYPE",

  // Email.
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_INVALID_TYPE: "EMAIL_INVALID_TYPE",
  EMAIL_INVALID: "EMAIL_INVALID",

  // Password.
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  PASSWORD_INVALID: "PASSWORD_INVALID",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_MISSING_UPPERCASE: "PASSWORD_MISSING_UPPERCASE",
  PASSWORD_MISSING_LOWERCASE: "PASSWORD_MISSING_LOWERCASE",
  PASSWORD_MISSING_NUMBER: "PASSWORD_MISSING_NUMBER",
  PASSWORD_MISSING_SPECIAL_CHAR: "PASSWORD_MISSING_SPECIAL_CHAR",

  /**
   * Access.
   */
  ACCESS_DEVICE_ID_INVALID: "ACCESS_DEVICE_ID_INVALID",
  ACCESS_SEND_VERIFICATION_EMAIL_SUCCESS:
    "ACCESS_SEND_VERIFICATION_EMAIL_SUCCESS",

  ACCESS_EMAIL_VERIFICATION_COOL_DOWN: "ACCESS_EMAIL_VERIFICATION_COOL_DOWN",
  ACCESS_EMAIL_VERIFICATION_LIMIT_REACHED:
    "ACCESS_EMAIL_VERIFICATION_LIMIT_REACHED",
  ACCESS_EMAIL_VERIFICATION_TOKEN_EXPIRED:
    "ACCESS_EMAIL_VERIFICATION_TOKEN_EXPIRED",
  ACCESS_EMAIL_VERIFICATION_TOKEN_INVALID:
    "ACCESS_EMAIL_VERIFICATION_TOKEN_INVALID",
  ACCESS_VERIFY_EMAIL_SUCCEEDED: "ACCESS_VERIFY_EMAIL_SUCCEEDED",

  ACCESS_VERIFY_EMAIL_TOKEN_REQUIRED: "ACCESS_VERIFY_EMAIL_TOKEN_REQUIRED",
  ACCESS_VERIFY_EMAIL_TOKEN_INVALID: "ACCESS_VERIFY_EMAIL_TOKEN_INVALID",

  /**
   * User.
   */
  USER_ID_REQUIRED: "USER_ID_REQUIRED",
  USER_ID_INVALID: "USER_ID_INVALID",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_ALREADY_VERIFIED_EMAIL: "USER_ALREADY_VERIFIED_EMAIL",
  USER_IS_NOT_REGISTERED: "USER_IS_NOT_REGISTERED",
  USER_NOT_LOGGED_IN: "USER_NOT_LOGGED_IN",

  USER_PHONE_NUMBER_REQUIRED: "USER_PHONE_NUMBER_REQUIRED",

  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_ALL_DEVICES_SUCCESS: "USER_LOGOUT_ALL_DEVICES_SUCCESS",

  USER_ADDRESS_REQUIRED: "USER_ADDRESS_REQUIRED",
  USER_ADDRESS_INVALID: "USER_ADDRESS_INVALID",
  USER_ADDRESS_ALREADY_EXISTS: "USER_ADDRESS_ALREADY_EXISTS",

  USER_ADD_ADDRESS_SUCCESS: "USER_ADD_ADDRESS_SUCCESS",

  // Key Token.
  KEY_TOKEN_ALREADY_EXISTS: "KEY_TOKEN_ALREADY_EXISTS",
  KEY_TOKEN_NOT_FOUND: "KEY_TOKEN_NOT_FOUND",

  /**
   * Shop.
   */
  SHOP_NOT_OWNED_BY_USER: "SHOP_NOT_OWNED_BY_USER",
  SHOP_REGISTER_FAILED: "SHOP_REGISTER_FAILED",

  SHOP_ID_REQUIRED: "SHOP_ID_REQUIRED",
  SHOP_ID_INVALID: "SHOP_ID_INVALID",

  SHOP_NAME_REQUIRED: "SHOP_NAME_REQUIRED",
  SHOP_NAME_INVALID_TYPE: "SHOP_NAME_INVALID_TYPE",
  SHOP_NAME_TOO_SHORT: "SHOP_NAME_TOO_SHORT",
  SHOP_NAME_EXCEEDED_MAX_LENGTH: "SHOP_NAME_EXCEEDED_MAX_LENGTH",

  SHOP_NOT_FOUND: "SHOP_NOT_FOUND",
  SHOP_INVALID_NAME: "SHOP_INVALID_NAME",
  SHOP_IS_NOT_REGISTERED: "SHOP_IS_NOT_REGISTERED",
  SHOP_ALREADY_EXISTS: "SHOP_ALREADY_EXISTS",
  SHOP_ALREADY_REGISTERED: "SHOP_ALREADY_REGISTERED",
  SHOP_REGISTER_SUCCESS: "SHOP_REGISTER_SUCCESS",

  SHOP_NOT_LOGGED_IN: "SHOP_NOT_LOGGED_IN",
  SHOP_LOGIN_SUCCESS: "SHOP_LOGIN_SUCCESS",

  SHOP_LOGOUT_SUCCESS: "SHOP_LOGOUT_SUCCESS",

  SHOP_UPDATE_INFORMATION_EMPTY: "SHOP_UPDATE_INFORMATION_EMPTY",

  SHOP_UPDATE_INFORMATION_SUCCESS: "SHOP_UPDATE_INFORMATION_SUCCESS",
  SHOP_UPDATE_INFORMATION_FAILURE: "SHOP_UPDATE_INFORMATION_FAILURE",

  SHOP_VERIFY_EMAIL_SUCCEEDED: "SHOP_VERIFY_EMAIL_SUCCEEDED",
  SHOP_SEND_VERIFICATION_EMAIL_SUCCEEDED:
    "SHOP_SEND_VERIFICATION_EMAIL_SUCCEEDED",

  SHOP_EMAIL_VERIFICATION_TOKEN_EXPIRED:
    "SHOP_EMAIL_VERIFICATION_TOKEN_EXPIRED",
  SHOP_EMAIL_VERIFICATION_TOKEN_INVALID:
    "SHOP_EMAIL_VERIFICATION_TOKEN_INVALID",
  SHOP_ALREADY_VERIFIED: "SHOP_ALREADY_VERIFIED",
  SHOP_ALREADY_CLOSED: "SHOP_ALREADY_CLOSED",

  SHOP_CLOSE_SUCCEEDED: "SHOP_CLOSE_SUCCEEDED",

  SHOP_VERIFY_EMAIL_TOKEN_REQUIRED: "SHOP_VERIFY_EMAIL_TOKEN_REQUIRED",
  SHOP_VERIFY_EMAIL_TOKEN_INVALID: "SHOP_VERIFY_EMAIL_TOKEN_INVALID",

  SHOP_CHANGE_CURRENCY_SUCCEEDED: "SHOP_CHANGE_CURRENCY_SUCCEEDED",
  SHOP_CURRENCY_NOT_SUPPORTED: "SHOP_CURRENCY_NOT_SUPPORTED",

  SHOP_CURRENCY_NOT_SET: "SHOP_CURRENCY_NOT_SET",

  /**
   * Product.
   */
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",

  PRODUCT_ID_REQUIRED: "PRODUCT_ID_REQUIRED",
  PRODUCT_ID_INVALID: "PRODUCT_ID_INVALID",

  PRODUCT_NAME_REQUIRED: "PRODUCT_NAME_REQUIRED",
  PRODUCT_NAME_INVALID: "PRODUCT_NAME_INVALID",

  PRODUCT_THUMB_REQUIRED: "PRODUCT_THUMB_REQUIRED",
  PRODUCT_THUMB_INVALID: "PRODUCT_THUMB_INVALID",

  PRODUCT_IMAGE_INVALID: "PRODUCT_IMAGE_INVALID",

  PRODUCT_DESCRIPTION_EXCEEDED_CHARACTER_LIMIT:
    "PRODUCT_DESCRIPTION_EXCEEDED_CHARACTER_LIMIT",

  PRODUCT_SHOP_REQUIRED: "PRODUCT_SHOP_REQUIRED",
  PRODUCT_SHOP_INVALID_TYPE: "PRODUCT_SHOP_INVALID_TYPE",

  PRODUCT_TYPE_INVALID: "PRODUCT_TYPE_INVALID",

  PRODUCT_PRICE_REQUIRED: "PRODUCT_PRICE_REQUIRED",
  PRODUCT_PRICE_INVALID: "PRODUCT_PRICE_INVALID",
  PRODUCT_PRICE_MUST_BE_POSITIVE: "PRODUCT_PRICE_MUST_BE_POSITIVE",

  PRODUCT_QUANTITY_INVALID: "PRODUCT_QUANTITY_INVALID",
  PRODUCT_QUANTITY_MUST_BE_NON_NEGATIVE:
    "PRODUCT_QUANTITY_MUST_BE_NON_NEGATIVE",

  PRODUCT_TYPE_UNSUPPORTED: "PRODUCT_TYPE_UNSUPPORTED",
  PRODUCT_AVERAGE_RATING_MUST_BE_GREATER_THAN_OR_EQUAL_TO_ONE:
    "PRODUCT_AVERAGE_RATING_MUST_BE_GREATER_THAN_OR_EQUAL_TO_ONE",
  PRODUCT_AVERAGE_RATING_MUST_BE_LESS_THAN_OR_EQUAL_TO_FIVE:
    "PRODUCT_AVERAGE_RATING_MUST_BE_LESS_THAN_OR_EQUAL_TO_FIVE",

  PRODUCT_CREATION_SUCCESS: "PRODUCT_CREATION_SUCCESS",
  PRODUCT_CREATION_FAILURE: "PRODUCT_CREATION_FAILURE",
  PRODUCT_CREATE_FAILED: "PRODUCT_CREATE_FAILED",

  PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",

  PRODUCT_FIND_SUCCESS: "PRODUCT_FIND_SUCCESS",

  PRODUCT_SEARCH_PUBLISHED_SUCCESS: "PRODUCT_SEARCH_PUBLISHED_SUCCESS",

  // Product publish.
  PRODUCT_ALREADY_PUBLISHED: "PRODUCT_ALREADY_PUBLISHED",
  PRODUCT_PUBLISH_SUCCESS: "PRODUCT_PUBLISH_SUCCESS",

  // Product unpublish.
  PRODUCT_ALREADY_DRAFT: "PRODUCT_ALREADY_DRAFT",
  PRODUCT_UNPUBLISH_SUCCESS: "PRODUCT_UNPUBLISH_SUCCESS",

  PRODUCT_FIND_DRAFT_PRODUCTS_SUCCESS: "PRODUCT_FIND_DRAFT_PRODUCTS_SUCCESS",
  PRODUCT_FIND_PUBLISHED_PRODUCTS_SUCCESS:
    "PRODUCT_FIND_PUBLISHED_PRODUCTS_SUCCESS",

  /**
   * Product category.
   */
  CATEGORY_ID_REQUIRED: "CATEGORY_ID_REQUIRED",
  CATEGORY_ID_INVALID: "CATEGORY_ID_INVALID",

  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",

  /**
   * Inventory.
   */
  INVENTORY_ID_REQUIRED: "INVENTORY_ID_REQUIRED",
  INVENTORY_ID_INVALID: "INVENTORY_ID_INVALID",

  INVENTORY_NOT_FOUND: "INVENTORY_NOT_FOUND",

  INVENTORY_STOCK_INVALID: "INVENTORY_STOCK_INVALID",
  INVENTORY_STOCK_MUST_BE_POSITIVE: "INVENTORY_STOCK_MUST_BE_POSITIVE",

  INVENTORY_CREATE_FAILED: "INVENTORY_CREATE_FAILED",
  INVENTORY_CREATE_SUCCEEDED: "INVENTORY_CREATE_SUCCEEDED",

  INVENTORY_UPDATE_SUCCEEDED: "INVENTORY_UPDATE_SUCCEEDED",

  INVENTORY_STOCK_INSUFFICIENT: "INVENTORY_STOCK_INSUFFICIENT",
  INVENTORY_RESERVATION_NOT_FOUND: "INVENTORY_RESERVATION_NOT_FOUND",

  INVENTORY_INSUFFICIENT_STOCK: "INVENTORY_INSUFFICIENT_STOCK",

  INVENTORY_REQUESTED_QUANTITY_EXCEEDS_AVAILABLE_STOCK:
    "INVENTORY_REQUESTED_QUANTITY_EXCEEDS_AVAILABLE_STOCK",

  INVENTORY_INCREASE_STOCK_SUCCEEDED: "INVENTORY_INCREASE_STOCK_SUCCEEDED",
  INVENTORY_DECREASE_STOCK_SUCCEEDED: "INVENTORY_DECREASE_STOCK_SUCCEEDED",

  /**
   * Cart.
   */
  CART_ID_REQUIRED: "CART_ID_REQUIRED",
  CART_ID_INVALID: "CART_ID_INVALID",

  CART_NOT_FOUND: "CART_NOT_FOUND",
  CART_CREATE_FAILED: "CART_CREATE_FAILED",

  CART_ADD_PRODUCT_TO_CART_FAILED: "CART_ADD_PRODUCT_TO_CART_FAILED",
  CART_ADD_PRODUCT_TO_CART_SUCCEEDED: "CART_ADD_PRODUCT_TO_CART_SUCCEEDED",

  CART_FIND_SUCCEEDED: "CART_FIND_SUCCEEDED",

  CART_REMOVE_PRODUCT_FROM_CART_SUCCEEDED:
    "CART_REMOVE_PRODUCT_FROM_CART_SUCCEEDED",

  CART_ITEM_QUANTITY_INVALID: "CART_ITEM_QUANTITY_INVALID",
  CART_ITEM_QUANTITY_MUST_BE_POSITIVE: "CART_ITEM_QUANTITY_MUST_BE_POSITIVE",

  /**
   * Pricing.
   */
  DISCOUNT_ID_REQUIRED: "DISCOUNT_ID_REQUIRED",
  DISCOUNT_ID_INVALID: "DISCOUNT_ID_INVALID",

  DISCOUNT_NAME_REQUIRED: "DISCOUNT_NAME_REQUIRED",
  DISCOUNT_NAME_INVALID: "DISCOUNT_NAME_INVALID",

  DISCOUNT_DESCRIPTION_REQUIRED: "DISCOUNT_DESCRIPTION_REQUIRED",
  DISCOUNT_DESCRIPTION_INVALID: "DISCOUNT_DESCRIPTION_INVALID",

  DISCOUNT_CODE_REQUIRED: "DISCOUNT_CODE_REQUIRED",
  DISCOUNT_CODE_INVALID: "DISCOUNT_CODE_INVALID",

  DISCOUNT_CREATE_FAILED: "DISCOUNT_CREATE_FAILED",
  DISCOUNT_CREATE_SUCCESS: "DISCOUNT_CREATE_SUCCESS",

  DISCOUNT_APPLIES_TO_NOT_SUPPORTED: "DISCOUNT_APPLIES_TO_NOT_SUPPORTED",
  DISCOUNT_APPLICABLE_PRODUCTS_REQUIRED:
    "DISCOUNT_APPLICABLE_PRODUCTS_REQUIRED",
  DISCOUNT_APPLICABLE_CATEGORIES_REQUIRED:
    "DISCOUNT_APPLICABLE_CATEGORIES_REQUIRED",

  DISCOUNT_ENDS_AT_MUST_BE_AFTER_STARTS_AT:
    "DISCOUNT_ENDS_AT_MUST_BE_AFTER_STARTS_AT",

  DISCOUNT_TYPE_NOT_SUPPORTED: "DISCOUNT_TYPE_NOT_SUPPORTED",
  DISCOUNT_MIN_ORDER_VALUE_NOT_MET: "DISCOUNT_MIN_ORDER_VALUE_NOT_MET",

  DISCOUNT_WITH_CODE_ALREADY_EXISTS: "DISCOUNT_WITH_CODE_ALREADY_EXISTS",

  DISCOUNT_NOT_FOUND: "DISCOUNT_NOT_FOUND",

  DISCOUNT_FIND_APPLICABLE_PRODUCTS_BY_DISCOUNT_CODE_SUCCESS:
    "DISCOUNT_FIND_APPLICABLE_PRODUCTS_BY_DISCOUNT_CODE_SUCCESS",

  DISCOUNT_FIND_DISCOUNTS_BY_SHOP: "DISCOUNT_FIND_DISCOUNTS_BY_SHOP",

  DISCOUNT_EXPIRED: "DISCOUNT_EXPIRED",

  DISCOUNT_NOT_STARTED: "DISCOUNT_NOT_STARTED",

  DISCOUNT_NOT_ACTIVE: "DISCOUNT_NOT_ACTIVE",
  DISCOUNT_LIMIT_REACHED: "DISCOUNT_LIMIT_REACHED",

  DISCOUNT_APPLY_DISCOUNT_TO_PRODUCTS: "DISCOUNT_APPLY_DISCOUNT_TO_PRODUCTS",

  DISCOUNT_FIND_SHOP_DISCOUNT_BY_DISCOUNT_CODE_SUCCESS:
    "DISCOUNT_FIND_SHOP_DISCOUNT_BY_DISCOUNT_CODE_SUCCESS",

  /**
   * Order.
   */
  ORDER_ID_REQUIRED: "ORDER_ID_REQUIRED",
  ORDER_ID_INVALID: "ORDER_ID_INVALID",

  ORDER_CHECKOUT_SUCCESS: "ORDER_CHECKOUT_SUCCESS",

  ORDER_ITEM_LIST_MUST_BE_NON_EMPTY: "ORDER_ITEM_LIST_MUST_BE_NON_EMPTY",

  ORDER_PRODUCT_LOCKED: "ORDER_PRODUCT_LOCKED",

  ORDER_CREATE_ORDER_FAILED: "ORDER_CREATE_ORDER_FAILED",

  ORDER_SHIPPING_ADDRESS_REQUIRED: "ORDER_SHIPPING_ADDRESS_REQUIRED",

  ORDER_CREATE_ORDER_SUCCEEDED: "ORDER_CREATE_ORDER_SUCCEEDED",

  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",

  ORDER_MULTIPLE_CURRENCIES_NOT_SUPPORTED:
    "ORDER_MULTIPLE_CURRENCIES_NOT_SUPPORTED",

  ORDER_PAYMENT_ALREADY_PROCESSED: "ORDER_PAYMENT_ALREADY_PROCESSED",

  /**
   * Payment.
   */
  PAYMENT_ID_REQUIRED: "PAYMENT_ID_REQUIRED",
  PAYMENT_ID_INVALID: "PAYMENT_ID_INVALID",

  PAYMENT_PROVIDER_UNSUPPORTED: "PAYMENT_PROVIDER_UNSUPPORTED",

  PAYMENT_STRIPE_CREATE_SESSION_FAILED: "PAYMENT_STRIPE_CREATE_SESSION_FAILED",

  PAYMENT_CREATE_SUCCEEDED: "PAYMENT_CREATE_SUCCEEDED",

  PAYMENT_METHOD_NOT_SUPPORTED: "PAYMENT_METHOD_NOT_SUPPORTED",

  /**
   * Shipping.
   */
  SHIPPING_PROVIDER_NOT_SUPPORTED: "SHIPPING_PROVIDER_NOT_SUPPORTED",
} as const;
