export const NOTIFICATION_TYPE = {
  VERIFICATION_EMAIL_SENT: "VERIFICATION_EMAIL_SENT",

  ORDER_CREATED: "ORDER_CREATED",

  ORDER_CONFIRMED: "ORDER_CONFIRMED",

  ORDER_SHIPPED: "ORDER_SHIPPED",

  ORDER_DELIVERED: "ORDER_DELIVERED",

  DISCOUNT_CREATED: "DISCOUNT_CREATED",

  PRODUCT_PUBLISHED: "PRODUCT_PUBLISHED",
} as const;

export const NOTIFICATION_STATUS = {
  PENDING: "PENDING",

  SENT: "SENT",

  FAILED: "FAILED",

  READ: "READ",
} as const;

export const NOTIFICATION_TITLE = {
  VERIFY_EMAIL: "VERIFY_EMAIL",
} as const;

export const NOTIFICATION_CONTENT = {
  VERIFY_EMAIL: "VERIFY_EMAIL",
} as const;
