export const NOTIFICATION_TYPE = {
  /**
   * Access.
   */
  ACCESS_VERIFY_EMAIL_SENT: "ACCESS_VERIFY_EMAIL_SENT",

  /**
   * Shop.
   */
  SHOP_VERIFY_EMAIL_SENT: "SHOP_VERIFY_EMAIL_SENT",
  SHOP_CLOSED: "SHOP_CLOSED",

  ORDER_CREATED: "ORDER_CREATED",

  ORDER_CONFIRMED: "ORDER_CONFIRMED",

  ORDER_SHIPPED: "ORDER_SHIPPED",

  ORDER_DELIVERED: "ORDER_DELIVERED",

  DISCOUNT_CREATED: "DISCOUNT_CREATED",

  PRODUCT_PUBLISHED: "PRODUCT_PUBLISHED",
} as const;

export const NOTIFICATION_STATUS = {
  PENDING: "PENDING",

  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",

  SENT: "SENT",
  READ: "READ",
} as const;

export const NOTIFICATION_TITLE = {
  /**
   * Access.
   */
  ACCESS_VERIFY_EMAIL: "ACCESS_VERIFY_EMAIL",

  /**
   * Shop.
   */
  SHOP_VERIFY_EMAIL: "SHOP_VERIFY_EMAIL",
  SHOP_CLOSE: "SHOP_CLOSE",
} as const;

export const NOTIFICATION_CONTENT = {
  /**
   * Access.
   */
  ACCESS_VERIFY_EMAIL: "ACCESS_VERIFY_EMAIL",

  /**
   * Shops.
   */
  SHOP_VERIFY_EMAIL: "SHOP_VERIFY_EMAIL",
  SHOP_CLOSE: "SHOP_CLOSE",
} as const;
