export const NOTIFICATION_TYPE = {
  EMAIL_VERIFICATION: "EMAIL_VERIFICATION",

  ORDER_CREATED: "ORDER_CREATED",

  ORDER_CONFIRMED: "ORDER_CONFIRMED",

  ORDER_SHIPPED: "ORDER_SHIPPED",

  ORDER_DELIVERED: "ORDER_DELIVERED",

  DISCOUNT_CREATED: "DISCOUNT_CREATED",

  PRODUCT_PUBLISHED: "PRODUCT_PUBLISHED",
} as const;

export const NOTIFICATION_STATUS = {
  PENDING: "PENDING",

  SENT: "SENT",

  FAILED: "FAILED",

  READ: "READ",
} as const;
