@baseApiUrl=http://127.0.0.1:20008/v1/api/shops

@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTBjNDFlYWY4N2JlMzU5MjI4NmE3NGUiLCJlbWFpbCI6Imx1dXRhbmh1bmdAZ21haWwuY29tIiwiaWF0IjoxNzc5MTg4MjIxLCJleHAiOjE3NzkzNjEwMjF9.vJeRhM07cHrR8dDnMTH4NylBwZAZ75sLrUMKjGT2YKE

### User registers a new shop successfully.
POST {{baseApiUrl}}/register
Content-Type: application/json
x-api-key: xxxxx
x-client-id: 6a0c41eaf87be3592286a74e
Authorization: {{accessToken}}

{
  "shopName": "Luu Tan Hung's Magic Shop"
}
